spring:
  application:
    name: scheduler
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/vortex
    username: vortex
    password: vortex
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceName: VortexScheduler
      org.quartz.threadPool.threadCount: 5

scheduler:
  leader-election:
    lock-id: 123456789