spring:
  application:
    name: scheduler
  quartz:
    job-store-type: memory
    properties:
      org.quartz.scheduler.instanceName: VortexScheduler
      org.quartz.threadPool.threadCount: 5
  kafka:
    bootstrap-servers: localhost:9092

scheduler:
  leader-election:
    lock-id: 123456789